apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: retaguarda-app-pdb
spec:
  minAvailable: 1  # or use maxUnavailable
  selector:
    matchLabels:
      app: retaguarda-app  # must match your Deployment's pod labels
