apiVersion: batch/v1
kind: CronJob
metadata:
  name: retaguarda-app
spec:
  schedule: "*/1 * * * *"  # A cada 2 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: tomcat
              image: devopsbemfacil/retaguarda_qa:1.5.3
              command: ["/bin/bash", "/usr/local/tomcat/webapps/ROOT/scripts-retaguarda/teste.sh"]
              imagePullPolicy: Always
          restartPolicy: OnFailure
