kind: ConfigMap
apiVersion: v1
metadata:
  name: retaguarda-configmap
data:
  GX_CONNECTION-DEFAULT-DB: IjEwLjg3LjIwOC4zIg==
  GX_CONNECTION-DEFAULT-DATASOURCE: QmVtZmFjaWxfcWE=
  GX_CONNECTION-DEFAULT-PORT: IjE0MzMi
  GX_CONNECTION-DEFAULT-USER: c3Fsc2VydmVy
  GX_CONNECTION-DEFAULT-PASSWORD: ZG11QW9ObHVGS25sbjl0bw==
