apiVersion: apps/v1
kind: Deployment
metadata:
  name: retaguarda-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retaguarda-app
  template:
    metadata:
      labels:
        app: retaguarda-app
    spec:
      containers:
      - name: tomcat
        image: 343236792564.dkr.ecr.us-east-1.amazonaws.com/bf-retaguarda:1.5.8-rds-priv
        imagePullPolicy: Always
        securityContext:
            runAsUser: 1000  # Non-root user ID
            runAsGroup: 1000  # Non-root group ID
            allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: retaguarda-configmap
        resources:
          requests:
            ephemeral-storage: "300Mi"
            cpu: "1000m"
            memory: "128Mi"
          limits:
            ephemeral-storage: "1Gi"
            cpu: "1000m"
            memory: "1Gi"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true