apiVersion: apps/v1
kind: Deployment
metadata:
  name: retaguarda-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retaguarda-app
  template:
    metadata:
      labels:
        app: retaguarda-app
    spec:
      containers:
      - name: tomcat
        image: devopsbemfacil/retaguarda_qa:1.5.3-rds-priv
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: retaguarda-configmap
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
