apiVersion: apps/v1
kind: Deployment
metadata:
  name: retaguarda-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retaguarda-app
  template:
    metadata:
      labels:
        app: retaguarda-app
    spec:
      containers:
      - name: tomcat
        image: 343236792564.dkr.ecr.us-east-1.amazonaws.com/bf-retaguarda:1.5.8-rds-priv
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: retaguarda-configmap
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
