apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vitor.tolao@bemfacil.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          route53:
            accessKeyIDSecretRef:
              name: route53-secret
              key: AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: route53-secret
              key: AWS_SECRET_ACCESS_KEY
            region: us-east-1  # Substitua pela região do seu Route 53
