apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: vitor.tolao@bemfacil.com.br
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z02607691M114MJUOFKRM #ZONEID_DO_SEU_ROUTE53
          accessKeyID: LHhpMEUvL3ppdWEwVEdLMDU1aVJxWnZnL2ZUUTdLN0tNVVZSbklnMEM=
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key